name: { { project_name.snakeCase() } }
description: { { { description } } }
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.0
  injectable: ^2.1.2
  provider: ^6.0.5

  floor: ^1.4.2
  rx_shared_preferences: ^3.1.0

  sqflite: ^2.3.0
  intl: ^0.19.0

  go_router: ^14.1.1

  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  floor_generator: ^1.4.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/

flutter_intl:
  enabled: true
